<a href="https://colab.research.google.com/github/deokwoo-han/abc/blob/master/10_12_2_Untitled30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pwd

/content


In [2]:
!ls -l

total 11256
-rw-r--r-- 1 root root 7563542 Oct 12 08:35 converted_savedmodel.zip
drwxr-xr-x 1 root root    4096 Oct  8 13:45 sample_data
-rw-r--r-- 1 root root 1259177 Oct 12 08:34 종이컵-samples.zip
-rw-r--r-- 1 root root 1582274 Oct 12 08:34 리모컨-samples.zip
-rw-r--r-- 1 root root 1109068 Oct 12 08:34 지우게-samples.zip


In [3]:
!mkdir ./remote

In [4]:
!unzip ./converted_savedmodel.zip

Archive:  ./converted_savedmodel.zip
   creating: model.savedmodel/
 extracting: model.savedmodel/saved_model.pb  
   creating: model.savedmodel/assets/
   creating: model.savedmodel/variables/
 extracting: model.savedmodel/variables/variables.index  
 extracting: model.savedmodel/variables/variables.data-00000-of-00001  
 extracting: labels.txt              


In [5]:
!unzip ./리모컨-samples.zip

Archive:  ./리모컨-samples.zip
 extracting: 0.jpg                   
 extracting: 1.jpg                   
 extracting: 2.jpg                   
 extracting: 3.jpg                   
 extracting: 4.jpg                   
 extracting: 5.jpg                   
 extracting: 6.jpg                   
 extracting: 7.jpg                   
 extracting: 8.jpg                   
 extracting: 9.jpg                   
 extracting: 10.jpg                  
 extracting: 11.jpg                  
 extracting: 12.jpg                  
 extracting: 13.jpg                  
 extracting: 14.jpg                  
 extracting: 15.jpg                  
 extracting: 16.jpg                  
 extracting: 17.jpg                  
 extracting: 18.jpg                  
 extracting: 19.jpg                  
 extracting: 20.jpg                  
 extracting: 21.jpg                  
 extracting: 22.jpg                  
 extracting: 23.jpg                  
 extracting: 24.jpg                  
 extracting: 25.jpg   

In [6]:
!mkdir ./remote

mkdir: cannot create directory ‘./remote’: File exists


In [7]:
!mv ./*.jpg ./remote/

In [8]:
!mv ./리모컨-samples.zip ./remote

In [9]:
#cd ./remote/

In [10]:
!unzip ./종이컵-samples.zip

Archive:  ./종이컵-samples.zip
 extracting: 0.jpg                   
 extracting: 1.jpg                   
 extracting: 2.jpg                   
 extracting: 3.jpg                   
 extracting: 4.jpg                   
 extracting: 5.jpg                   
 extracting: 6.jpg                   
 extracting: 7.jpg                   
 extracting: 8.jpg                   
 extracting: 9.jpg                   
 extracting: 10.jpg                  
 extracting: 11.jpg                  
 extracting: 12.jpg                  
 extracting: 13.jpg                  
 extracting: 14.jpg                  
 extracting: 15.jpg                  
 extracting: 16.jpg                  
 extracting: 17.jpg                  
 extracting: 18.jpg                  
 extracting: 19.jpg                  
 extracting: 20.jpg                  
 extracting: 21.jpg                  
 extracting: 22.jpg                  
 extracting: 23.jpg                  
 extracting: 24.jpg                  
 extracting: 25.jpg   

In [11]:
!mkdir ./cup

In [12]:
!mv ./*.jpg ./cup/

In [13]:
!mv ./종이컵-samples.zip ./cup

In [14]:
#%cd ./cup/

In [15]:
!unzip ./지우게-samples.zip

Archive:  ./지우게-samples.zip
 extracting: 0.jpg                   
 extracting: 1.jpg                   
 extracting: 2.jpg                   
 extracting: 3.jpg                   
 extracting: 4.jpg                   
 extracting: 5.jpg                   
 extracting: 6.jpg                   
 extracting: 7.jpg                   
 extracting: 8.jpg                   
 extracting: 9.jpg                   
 extracting: 10.jpg                  
 extracting: 11.jpg                  
 extracting: 12.jpg                  
 extracting: 13.jpg                  
 extracting: 14.jpg                  
 extracting: 15.jpg                  
 extracting: 16.jpg                  
 extracting: 17.jpg                  
 extracting: 18.jpg                  
 extracting: 19.jpg                  
 extracting: 20.jpg                  
 extracting: 21.jpg                  
 extracting: 22.jpg                  
 extracting: 23.jpg                  
 extracting: 24.jpg                  
 extracting: 25.jpg   

In [16]:
!mkdir ./eraser

In [17]:
!mv ./*.jpg ./eraser/

In [18]:
!mv ./지우게-samples.zip ./eraser

In [19]:
#%cd ./eraser/

In [20]:
!ls -l

total 7412
-rw-r--r-- 1 root root 7563542 Oct 12 08:35 converted_savedmodel.zip
drwxr-xr-x 2 root root    4096 Oct 12 08:36 cup
drwxr-xr-x 2 root root    4096 Oct 12 08:36 eraser
-rw-r--r-- 1 root root      36 Oct 12 06:53 labels.txt
drwxr-xr-x 4 root root    4096 Oct 12 06:53 model.savedmodel
drwxr-xr-x 2 root root    4096 Oct 12 08:35 remote
drwxr-xr-x 1 root root    4096 Oct  8 13:45 sample_data


In [21]:
!pwd

/content


In [22]:
#%cd /content/

In [23]:
#%cd ..

In [24]:
#!pwd

In [25]:
#%cd /content/

In [26]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [27]:
from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

In [28]:
# Load the model
model = load_model('./model.savedmodel')
#('keras_model.h5')

In [29]:
model.summary()

Model: "sequential_40"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential_37 (Sequential)   (None, 1280)              410208    
_________________________________________________________________
sequential_39 (Sequential)   (None, 3)                 128400    
Total params: 538,608
Trainable params: 524,528
Non-trainable params: 14,080
_________________________________________________________________


In [30]:
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32) #인풋 사이즈가 224로 매핑

In [79]:
image = Image.open('./eraser/129.jpg') #컵으로 바꿀 수 있음

In [80]:
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

In [81]:
image_array = np.asarray(image)

In [82]:
image_array.shape

(224, 224, 3)

In [83]:
image_array[:10, :10, 0] #0은 레드, 뒤에 1을 넣으면 그린 채널

array([[107, 107, 107, 107, 108, 108, 108, 108, 109, 109],
       [107, 107, 107, 107, 108, 108, 108, 108, 109, 109],
       [107, 107, 108, 108, 108, 108, 108, 109, 109, 109],
       [108, 108, 108, 108, 108, 109, 109, 109, 109, 109],
       [108, 108, 109, 109, 109, 109, 109, 109, 109, 109],
       [109, 109, 109, 109, 109, 109, 109, 109, 109, 109],
       [109, 109, 109, 109, 109, 109, 109, 109, 110, 110],
       [110, 110, 110, 110, 110, 109, 109, 109, 111, 111],
       [109, 109, 109, 109, 109, 110, 110, 111, 111, 111],
       [109, 109, 109, 109, 109, 110, 110, 111, 111, 112]], dtype=uint8)

In [84]:
image_array[:10, :10, 1]

array([[108, 108, 108, 108, 109, 109, 108, 108, 109, 109],
       [108, 108, 108, 108, 109, 108, 108, 108, 109, 109],
       [108, 108, 109, 109, 109, 108, 108, 109, 109, 109],
       [109, 109, 109, 109, 108, 109, 109, 109, 109, 109],
       [109, 109, 110, 110, 109, 109, 109, 109, 109, 109],
       [110, 109, 109, 109, 109, 109, 109, 109, 109, 109],
       [109, 109, 109, 109, 109, 109, 109, 109, 110, 110],
       [110, 110, 110, 110, 110, 109, 109, 109, 111, 111],
       [109, 109, 109, 109, 109, 110, 110, 111, 111, 111],
       [109, 109, 109, 109, 109, 110, 110, 111, 111, 112]], dtype=uint8)

In [85]:
image_array[:10, :10, 2] #블루

array([[103, 103, 103, 103, 104, 104, 106, 106, 107, 107],
       [103, 103, 103, 103, 104, 106, 106, 106, 107, 107],
       [103, 103, 104, 104, 104, 106, 106, 107, 107, 109],
       [104, 104, 104, 104, 106, 107, 107, 107, 107, 109],
       [104, 104, 105, 105, 107, 107, 107, 107, 107, 109],
       [105, 107, 107, 107, 107, 107, 107, 107, 107, 109],
       [107, 107, 107, 107, 107, 107, 107, 107, 110, 110],
       [108, 108, 108, 108, 108, 107, 107, 109, 111, 111],
       [107, 107, 107, 107, 107, 108, 110, 111, 111, 111],
       [107, 107, 109, 109, 109, 110, 110, 111, 111, 112]], dtype=uint8)

In [86]:
#normalized_image_array[:10, :10, 2] #오류남

In [87]:
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
#255면 0에서 1값으로 바꿔버리는, 이미지 자체를 노멀라이즈

In [88]:
#normalized_image_array = (image_array.astype(np.float32) / 255)

In [89]:
data[0] = normalized_image_array

In [90]:
prediction = model.predict(data)

In [91]:
prediction

array([[9.9167073e-01, 8.3280103e-03, 1.3295695e-06]], dtype=float32)

In [92]:
print(prediction) #순서대로 나와야 하는데...
#소프트 맥스 값으로 해서 제일 큰 값이 중간에 나와야
#모델에 순서를 안 가르쳐 줌
#label.txt를 안 읽음
#디렉토리 이름을 바꿈

[[9.9167073e-01 8.3280103e-03 1.3295695e-06]]


In [93]:
prediction.max()

0.9916707

In [94]:
#소프트맥스 3개의 확률 값

In [95]:
prediction.round(2)

array([[0.99, 0.01, 0.  ]], dtype=float32)

In [96]:
# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
##data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
# Replace this with the path to your image
##image = Image.open('<IMAGE_PATH>')
#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
##size = (224, 224)
##image = ImageOps.fit(image, size, Image.ANTIALIAS)

#turn the image into a numpy array
##image_array = np.asarray(image)
# Normalize the image
##normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1
# Load the image into the array
##data[0] = normalized_image_array

# run the inference
##prediction = model.predict(data)
##print(prediction)

In [97]:
!pip list
#Tensorflow.__version__
#예제 깃허브
#deeplearning with python notebooks

Package                       Version
----------------------------- --------------
absl-py                       0.12.0
alabaster                     0.7.12
albumentations                0.1.12
altair                        4.1.0
appdirs                       1.4.4
argcomplete                   1.12.3
argon2-cffi                   21.1.0
arviz                         0.11.4
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
atari-py                      0.2.9
atomicwrites                  1.4.0
attrs                         21.2.0
audioread                     2.1.9
autograd                      1.3
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        4.1.0
blis                          0.4.1
bokeh                         2.3.3
Bottleneck                    1.3.2
branca                        0.4.2
bs4                           0.0.1
CacheControl

In [98]:
import tensorflow

In [99]:
tensorflow.__version__

'2.6.0'

In [100]:
import keras

In [101]:
keras.__version__

'2.6.0'

In [102]:
#!pip -r requirements.txt