<a href="https://colab.research.google.com/github/deokwoo-han/abc/blob/master/10_1_2_DNN_ipynb_sc%2C_batch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import tensorflow as tf

In [ ]:
df = pd.read_csv('credit_cards_dataset.csv')

In [ ]:
X = df.drop(['default.payment.next.month'], axis=1).values

In [ ]:
Y = df['default.payment.next.month'].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

Standard Scale

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
#X_train = sc.fit_transform(X_train)

In [ ]:
#pd.DataFrame(X_train).describe().round(2)#평균값이 제로 분산값이 1, 함수영 언어, 데이터셋만 준비

In [ ]:
#X_test = sc.fit_transform(X_test)

In [ ]:
#0과 1로 갈라줘야 함

In [ ]:
from tensorflow import keras#모델만 준비
from tensorflow.keras import layers

# Create a network with 1 linear unit #24 하나는 모델이 망가짐, 출력값을 더 큰 걸로...
model = keras.Sequential([
    layers.Dense(units=30, input_shape=[24], activation='relu'), #출력값만 바꿀 것 #레이어를 백개 하면 안좋게? 30 50 30 20 10
    layers.Dropout(rate=0.3),
    layers.BatchNormalization(),

    #layers.Dense(units=50, activation='relu'), #배치는 두번 만 넣어도 상관 없음
    #layers.Dropout(rate=0.3),
    #layers.BatchNormalization(),
    
    layers.Dense(units=30, activation='relu'),
    layers.Dropout(rate=0.3),
    layers.BatchNormalization(),

    layers.Dense(units=15, activation='relu'),
    layers.Dropout(rate=0.3),

    layers.Dense(units=5, activation='relu'),
    layers.Dropout(rate=0.3), #모델이 네개, 인풋 아웃풋은 빼고 히든 레이어는 몇개? 

    layers.Dense(units=1, activation='sigmoid')#0과 1값으로 바꿔주는 함수, 액티베이션 함수를 그냥 쓴다, 두개2로 한다면은 또 바뀜
])#하나짜리 쉬운 것
#변수 바꾸기 안에 숫자, 레이어 늘리기 줄이기 덴스 개수

In [ ]:
#from tensorflow import keras#모델만 준비
#from tensorflow.keras import layers

# Create a network with 1 linear unit #24 하나는 모델이 망가짐, 출력값을 더 큰 걸로...
#model = keras.Sequential([
#    layers.Dense(units=30, input_shape=[24], activation='relu'), #출력값만 바꿀 것 #레이어를 백개 하면 안좋게? 30 50 30 20 10
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=50, activation='relu'), #배치는 두번 만 넣어도 상관 없음
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=30, activation='relu'),
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=15, activation='relu'),
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=5, activation='relu'),
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=1, activation='sigmoid')#0과 1값으로 바꿔주는 함수, 액티베이션 함수를 그냥 쓴다, 두개2로 한다면은 또 바뀜
#])#하나짜리 쉬운 것
#변수 바꾸기 안에 숫자, 레이어 늘리기 줄이기 덴스 개수

In [ ]:
#keras.Sequential([
    # ...
#    layers.Dropout(rate=0.3), # apply 30% dropout to the next layer
#    layers.Dense(16),
    # ...
#])

In [ ]:
#from tensorflow import keras#모델만 준비
#from tensorflow.keras import layers

# Create a network with 1 linear unit #24 하나는 모델이 망가짐, 출력값을 더 큰 걸로...
#model = keras.Sequential([
#    layers.Dense(units=50, input_shape=[24]), #출력값만 바꿀 것 #레이어를 백개 하면 안좋게?
#    layers.Dense(units=60),
#    layers.Dense(units=25),
#    layers.Dense(units=10),
#    layers.Dense(units=1, activation='sigmoid')#0과 1값으로 바꿔주는 함수, 액티베이션 함수를 그냥 쓴다, 두개2로 한다면은 또 바뀜
#])#하나짜리 쉬운 것

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_10 (Dense)             (None, 30)                750       
_________________________________________________________________
dropout_8 (Dropout)          (None, 30)                0         
_________________________________________________________________
batch_normalization_4 (Batch (None, 30)                120       
_________________________________________________________________
dense_11 (Dense)             (None, 30)                930       
_________________________________________________________________
dropout_9 (Dropout)          (None, 30)                0         
_________________________________________________________________
batch_normalization_5 (Batch (None, 30)                120       
_________________________________________________________________
dense_12 (Dense)             (None, 15)               

In [ ]:
model.compile(optimizer='adam', loss=tf.keras.losses.BinaryCrossentropy(), metrics=[tf.keras.metrics.BinaryAccuracy()])
#어뎁티브 메트릭을 찾는 여러가지 방법
#로스는 일단 바이너리 크로스 엔트로피로 쓴다.

In [ ]:
#컴파일 옵션을 준다

In [ ]:
#미분의 절편을 찾을 방법은 무엇인가? 

In [ ]:
model.fit(X_train, Y_train, epochs=30, shuffle=True, verbose='auto', batch_size=64)#epoch 60?
#모델 로드
#학습 몇번이 세번재, 네번째는 포커 등에서 패섞고, 다섯번째는 과정보여주기#버킷사이즈가 64로 두배로 커짐 657이 얼마로? 329로 바뀔것
#또한 번 체크하고 로스 값 비교하고 등등

Epoch 1/30
329/329 [==============================] - 2s 3ms/step - loss: 0.6153 - binary_accuracy: 0.7149
Epoch 2/30
329/329 [==============================] - 1s 3ms/step - loss: 0.5496 - binary_accuracy: 0.7734
Epoch 3/30
329/329 [==============================] - 1s 3ms/step - loss: 0.5361 - binary_accuracy: 0.7763
Epoch 4/30
329/329 [==============================] - 1s 3ms/step - loss: 0.5297 - binary_accuracy: 0.7770
Epoch 5/30
329/329 [==============================] - 1s 2ms/step - loss: 0.5236 - binary_accuracy: 0.7771
Epoch 6/30
329/329 [==============================] - 1s 2ms/step - loss: 0.5235 - binary_accuracy: 0.7773
Epoch 7/30
329/329 [==============================] - 1s 3ms/step - loss: 0.5213 - binary_accuracy: 0.7773
Epoch 8/30
329/329 [==============================] - 1s 3ms/step - loss: 0.5195 - binary_accuracy: 0.7773
Epoch 9/30
329/329 [==============================] - 1s 2ms/step - loss: 0.5188 - binary_accuracy: 0.7773
Epoch 10/30
329/329 [================

In [ ]:
#from keras.models import load_model
#model = load_model('my_model.h5')

In [ ]:
model.weights#이것이 2471개의 학습된 내용, 선형 회귀 coefficient 처럼
#0은 인풋 24, 출력 30, 0은 인풋 쉐이프가 24개가 늘어남

[<tf.Variable 'dense_10/kernel:0' shape=(24, 30) dtype=float32, numpy=
 array([[-2.19709322e-01,  2.13717863e-01,  1.35689396e-02,
         -1.10149221e-03,  9.75991279e-05,  5.85649982e-02,
          8.00167397e-02, -8.64953250e-02, -2.32096314e-01,
         -1.65823415e-01, -1.13622852e-01, -3.14499214e-02,
         -3.25786531e-01, -1.75455019e-01, -9.09688473e-02,
          1.80069223e-01, -1.26907945e-01,  5.54966256e-02,
         -1.58386007e-01,  1.72668286e-02, -9.64865535e-02,
          1.43002467e-02,  1.54098392e-01, -1.20454133e-02,
         -1.98080182e-01, -7.58640617e-02, -9.70247108e-03,
         -2.69827932e-01,  1.02345474e-01,  1.95148494e-02],
        [-2.42493257e-01, -1.99995525e-02,  1.90859067e-03,
         -3.16986442e-01, -1.19324028e-02,  3.36059704e-02,
         -3.56835872e-01, -7.66384825e-02,  3.51588018e-02,
         -2.35452369e-01, -1.73116431e-01, -2.45453954e-01,
         -2.51679480e-01, -3.27091038e-01,  3.63738984e-01,
         -9.64222476e-02,  8

In [ ]:
y_predict = model.predict(X_test)

In [ ]:
#저장할 것

In [ ]:
#from keras.models import load_model

#model.save('my_model.h5')

In [ ]:
y_predict[:30]

array([[0.24285764],
       [0.22533894],
       [0.27686545],
       [0.14910972],
       [0.24074745],
       [0.16576037],
       [0.19412237],
       [0.22580338],
       [0.12136772],
       [0.19865182],
       [0.28649443],
       [0.1147294 ],
       [0.2411623 ],
       [0.29974797],
       [0.15196651],
       [0.2411623 ],
       [0.18110222],
       [0.29892063],
       [0.20294529],
       [0.30252653],
       [0.16533467],
       [0.28781074],
       [0.21590868],
       [0.2411623 ],
       [0.2411623 ],
       [0.19256783],
       [0.14444304],
       [0.29766735],
       [0.14498797],
       [0.16844532]], dtype=float32)

In [ ]:
import numpy as np

In [ ]:
y_predict = np.rint(y_predict)

In [ ]:
y_predict[:30]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
recall_score(Y_test, y_predict)

0.0

In [ ]:
#표상 러닝은 주관적?
#0.21683673469387754
#0.1836734693877551
#0.24948979591836734
#0.2545918367346939

In [ ]:
#레이어 줄인 0.20408163265306123

In [ ]:
tf.__version__

'2.6.0'

In [ ]:
#늘린 0.1576530612244898

In [ ]:
#변수를 바꾼 0.2755102040816326

In [ ]:
#0.30306122448979594 같은 원본인데...
#0.24693877551020407

In [ ]:
#편차가 심한 걸 어덯게 해결하는가?
#웨이트의 값을 바꾸는 것

In [ ]:
#0.21581632653061225

In [ ]:
#0.3
#0.26326530612244897

In [ ]:
#0.21785714285714286
#0.1903061224489796
#0.06581632653061224

In [ ]:
#레이러 줄고 바꾼 버전 0.21479591836734693
#0.23265306122448978

In [ ]:
#액티베이션 추가 0.286734693877551
#0.27908163265306124
#0.27908163265306124
#0.32857142857142857

In [ ]:
#배치 노멀라이제이션 추가 0.3229591836734694

In [ ]:
#0.22857142857142856 0.23214285714285715

In [ ]:
#최종본 0.25816326530612244 0.26887755102040817