<a href="https://colab.research.google.com/github/deokwoo-han/abc/blob/master/10_1_1_DNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import tensorflow as tf

In [ ]:
df = pd.read_csv('credit_cards_dataset.csv')

In [ ]:
X = df.drop(['default.payment.next.month'], axis=1).values

In [ ]:
Y = df['default.payment.next.month'].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

Standard Scale

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
X_train = sc.fit_transform(X_train)

In [ ]:
pd.DataFrame(X_train).describe().round(2)#평균값이 제로 분산값이 1, 함수영 언어, 데이터셋만 준비

0         1         2   ...        21        22        23
count  21000.00  21000.00  21000.00  ...  21000.00  21000.00  21000.00
mean      -0.00     -0.00     -0.00  ...      0.00      0.00     -0.00
std        1.00      1.00      1.00  ...      1.00      1.00      1.00
min       -1.73     -1.22     -1.24  ...     -0.30     -0.31     -0.30
25%       -0.87     -0.91     -1.24  ...     -0.29     -0.29     -0.29
50%        0.01     -0.21      0.81  ...     -0.21     -0.21     -0.21
75%        0.86      0.56      0.81  ...     -0.06     -0.05     -0.07
max        1.73      6.44      0.81  ...     38.23     26.62     29.46

[8 rows x 24 columns]

In [ ]:
X_test = sc.fit_transform(X_test)

In [ ]:
#0과 1로 갈라줘야 함

In [ ]:
#from tensorflow import keras#모델만 준비
#from tensorflow.keras import layers

# Create a network with 1 linear unit #24 하나는 모델이 망가짐, 출력값을 더 큰 걸로...
#model = keras.Sequential([
#    layers.Dense(units=30, input_shape=[24], activation='relu'), #출력값만 바꿀 것 #레이어를 백개 하면 안좋게? 30 50 30 20 10
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),

    #layers.Dense(units=50, activation='relu'), #배치는 두번 만 넣어도 상관 없음
    #layers.Dropout(rate=0.3),
    #layers.BatchNormalization(),
    
 #   layers.Dense(units=30, activation='relu'),
 #   layers.Dropout(rate=0.3),
 #   layers.BatchNormalization(),

  #  layers.Dense(units=15, activation='relu'),
  #  layers.Dropout(rate=0.3),

  #  layers.Dense(units=5, activation='relu'),
  #  layers.Dropout(rate=0.3), #모델이 네개, 인풋 아웃풋은 빼고 히든 레이어는 몇개? 

   # layers.Dense(units=1, activation='sigmoid')#0과 1값으로 바꿔주는 함수, 액티베이션 함수를 그냥 쓴다, 두개2로 한다면은 또 바뀜
#])#하나짜리 쉬운 것
#변수 바꾸기 안에 숫자, 레이어 늘리기 줄이기 덴스 개수

In [ ]:
#from tensorflow import keras#모델만 준비
#from tensorflow.keras import layers

# Create a network with 1 linear unit #24 하나는 모델이 망가짐, 출력값을 더 큰 걸로...
#model = keras.Sequential([
#    layers.Dense(units=30, input_shape=[24], activation='relu'), #출력값만 바꿀 것 #레이어를 백개 하면 안좋게? 30 50 30 20 10
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=50, activation='relu'), #배치는 두번 만 넣어도 상관 없음
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=30, activation='relu'),
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=15, activation='relu'),
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=5, activation='relu'),
#    layers.Dropout(rate=0.3),
#    layers.BatchNormalization(),
#    layers.Dense(units=1, activation='sigmoid')#0과 1값으로 바꿔주는 함수, 액티베이션 함수를 그냥 쓴다, 두개2로 한다면은 또 바뀜
#])#하나짜리 쉬운 것
#변수 바꾸기 안에 숫자, 레이어 늘리기 줄이기 덴스 개수

In [ ]:
#keras.Sequential([
    # ...
#    layers.Dropout(rate=0.3), # apply 30% dropout to the next layer
#    layers.Dense(16),
    # ...
#])

In [ ]:
#from tensorflow import keras#모델만 준비
#from tensorflow.keras import layers

# Create a network with 1 linear unit #24 하나는 모델이 망가짐, 출력값을 더 큰 걸로...
#model = keras.Sequential([
#    layers.Dense(units=50, input_shape=[24]), #출력값만 바꿀 것 #레이어를 백개 하면 안좋게?
#    layers.Dense(units=60),
#    layers.Dense(units=25),
#    layers.Dense(units=10),
#    layers.Dense(units=1, activation='sigmoid')#0과 1값으로 바꿔주는 함수, 액티베이션 함수를 그냥 쓴다, 두개2로 한다면은 또 바뀜
#])#하나짜리 쉬운 것

In [ ]:
#model.summary()

In [ ]:
#model.compile(optimizer='adam', loss=tf.keras.losses.BinaryCrossentropy(), metrics=[tf.keras.metrics.BinaryAccuracy()])
#어뎁티브 메트릭을 찾는 여러가지 방법
#로스는 일단 바이너리 크로스 엔트로피로 쓴다.

In [ ]:
#컴파일 옵션을 준다

In [ ]:
#미분의 절편을 찾을 방법은 무엇인가? 

In [ ]:
##model.fit(X_train, Y_train, epochs=30, shuffle=True, verbose='auto', batch_size=64)#epoch 60?
#모델 로드
#학습 몇번이 세번재, 네번째는 포커 등에서 패섞고, 다섯번째는 과정보여주기#버킷사이즈가 64로 두배로 커짐 657이 얼마로? 329로 바뀔것
#또한 번 체크하고 로스 값 비교하고 등등

In [ ]:
from keras.models import load_model
model = load_model('my_model.h5')

In [ ]:
model.weights#이것이 2471개의 학습된 내용, 선형 회귀 coefficient 처럼
#0은 인풋 24, 출력 30, 0은 인풋 쉐이프가 24개가 늘어남

[<tf.Variable 'dense/kernel:0' shape=(24, 30) dtype=float32, numpy=
 array([[-1.37250898e-02,  3.45837355e-01, -7.73706138e-02,
          5.35016134e-03, -1.50074130e-02,  5.49446642e-02,
          4.08389680e-02, -1.65561646e-01,  2.87647426e-01,
         -4.07301933e-01,  1.90735862e-01, -6.80424422e-02,
          1.86206743e-01, -1.08590603e-01,  2.93035735e-03,
          2.13422924e-01, -4.37277630e-02,  7.05514103e-02,
         -4.30322476e-02,  1.48118734e-01,  1.77261785e-01,
         -9.53547135e-02,  4.24312316e-02,  7.10139200e-02,
          1.56776771e-01,  7.37709925e-02,  1.73988312e-01,
          1.02293201e-01, -7.46485814e-02,  2.08471958e-02],
        [ 7.99127221e-02,  4.13623720e-01, -3.81893545e-01,
          8.13136324e-02, -1.55346245e-01, -2.82241702e-01,
         -1.13435395e-01, -6.87983632e-02,  3.27375561e-01,
         -2.68772185e-01,  1.32300958e-01,  1.46954834e-01,
         -1.19333349e-01, -4.39380527e-01,  2.58104950e-02,
          9.99010056e-02, -1.38

In [ ]:
y_predict = model.predict(X_test)

In [ ]:
#저장할 것

In [ ]:
#from keras.models import load_model

#model.save('my_model.h5')

In [ ]:
y_predict[:30]

array([[0.20511752],
       [0.08320108],
       [0.1375683 ],
       [0.14333266],
       [0.15300608],
       [0.18959978],
       [0.39706916],
       [0.34208417],
       [0.11068565],
       [0.12290815],
       [0.5651974 ],
       [0.09388542],
       [0.16008484],
       [0.7240167 ],
       [0.17823762],
       [0.1594826 ],
       [0.11721653],
       [0.21919611],
       [0.23111907],
       [0.5505798 ],
       [0.1438669 ],
       [0.22019956],
       [0.20078406],
       [0.12588349],
       [0.16105539],
       [0.237526  ],
       [0.20556429],
       [0.51053697],
       [0.1940895 ],
       [0.20371452]], dtype=float32)

In [ ]:
import numpy as np

In [ ]:
y_predict = np.rint(y_predict)

In [ ]:
y_predict[:30]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
recall_score(Y_test, y_predict)

0.23214285714285715

In [ ]:
#표상 러닝은 주관적?
#0.21683673469387754
#0.1836734693877551
#0.24948979591836734
#0.2545918367346939

In [ ]:
#레이어 줄인 0.20408163265306123

In [ ]:
tf.__version__

'2.6.0'

In [ ]:
#늘린 0.1576530612244898

In [ ]:
#변수를 바꾼 0.2755102040816326

In [ ]:
#0.30306122448979594 같은 원본인데...
#0.24693877551020407

In [ ]:
#편차가 심한 걸 어덯게 해결하는가?
#웨이트의 값을 바꾸는 것

In [ ]:
#0.21581632653061225

In [ ]:
#0.3
#0.26326530612244897

In [ ]:
#0.21785714285714286
#0.1903061224489796
#0.06581632653061224

In [ ]:
#레이러 줄고 바꾼 버전 0.21479591836734693
#0.23265306122448978

In [ ]:
#액티베이션 추가 0.286734693877551
#0.27908163265306124
#0.27908163265306124
#0.32857142857142857

In [ ]:
#배치 노멀라이제이션 추가 0.3229591836734694

In [ ]:
#0.22857142857142856 0.23214285714285715

In [ ]:
#최종본 0.25816326530612244 0.26887755102040817